use_frameworks!

platform :ios, '8.0'

target 'KWOCMacroDefinite_Example' do
  pod 'KWOCMacroDefinite', :path => '../'

  target 'KWOCMacroDefinite_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
